---
name: Hass.io Access Point
version: 0.5.2.1
slug: hassio-access-point
description: Create a WiFi access point to directly connect devices to Home Assistant
arch: [armhf, armv7, aarch64, amd64, i386]
url: https://github.com/mattlongman/hassio-access-point
startup: system
boot: auto
host_network: true
apparmor: true
host_dbus: true
privileged:
  - NET_ADMIN
init: false
options:
  ssid:
  wpa_passphrase:
  channel: 6
  address: 192.168.99.1
  netmask: 255.255.255.0
  broadcast: 192.168.99.255
  interface: wlan0
  hide_ssid: false
  dhcp: false
  dhcp_start_addr: 192.168.99.10
  dhcp_end_addr: 192.168.99.20
  allow_mac_addresses: []
  deny_mac_addresses: []
  debug: 0
  hostapd_config_override: []
  client_internet_access: false
  client_dns_override: []
  dnsmasq_config_override: []
schema:
  ssid: match(^.{2,32}$)
  wpa_passphrase: password
  channel: int(1,13)
  address: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  netmask: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  broadcast: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  interface: str
  hide_ssid: bool
  dhcp: bool
  dhcp_start_addr: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  dhcp_end_addr: match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  allow_mac_addresses:
    - match(^([0-9a-fA-F]{2}:){4}[0-9a-fA-F]{2})?
  deny_mac_addresses:
    - match(^([0-9a-fA-F]{2}:){4}[0-9a-fA-F]{2})?
  debug: int(0,2)
  hostapd_config_override:
    - str?
  client_internet_access: bool
  client_dns_override:
    - match(^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$)
  dnsmasq_config_override:
    - str?
